defmodule SoundaiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :soundai

  # The session will be stored in the cookie and signed, this means its
  # contents can be read but not tampered with. The signing salt is secret
  # material: it lives exclusively in configuration (`signing_salt:` under
  # `config :soundai, SoundaiWeb.Endpoint`) — never in this file. Dev/test use
  # a throwaway fallback; production takes SOUNDAI_SIGNING_SALT (or derives
  # one from SECRET_KEY_BASE) in config/runtime.exs. Rotating the salt
  # invalidates existing signed sessions, which is acceptable for this app.
  @session_defaults [
    store: :cookie,
    key: "_soundai_key",
    same_site: "Lax"
  ]

  # Enable cross-origin isolation so onnxruntime-web can run WASM with
  # multiple threads (SharedArrayBuffer). This makes Whisper inference on
  # the WASM/CPU fallback several times faster. `credentialless` (instead of
  # `require-corp`) keeps CDN model/WASM fetches working without CORP headers.
  plug :cross_origin_isolation_headers

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :soundai,
    gzip: not code_reloading?,
    only: SoundaiWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  # Request logging streams recent request URLs/status/timing to anyone
  # holding the query param/cookie, so it is a development-only affordance:
  # compiled out whenever code reloading is off (test/prod).
  if code_reloading? do
    plug Phoenix.LiveDashboard.RequestLogger,
      param_key: "request_logger",
      cookie_key: "request_logger"
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug :signed_session
  plug SoundaiWeb.Router

  # Plug.Session options are resolved per request so the configured salt is
  # read from application env at runtime (config/config.exs and the overrides
  # in config/runtime.exs apply even inside a release, where @session_options
  # would have been frozen at build time).
  defp signed_session(conn, _opts) do
    signing_salt =
      :soundai
      |> Application.fetch_env!(SoundaiWeb.Endpoint)
      |> Keyword.fetch!(:signing_salt)

    Plug.Session.call(
      conn,
      Plug.Session.init(Keyword.put(@session_defaults, :signing_salt, signing_salt))
    )
  end

  defp cross_origin_isolation_headers(conn, _opts) do
    conn
    |> Plug.Conn.put_resp_header("cross-origin-opener-policy", "same-origin")
    |> Plug.Conn.put_resp_header("cross-origin-embedder-policy", "credentialless")
  end
end
