defmodule Soundai.TTS.FakeAdapter do
  @moduledoc """
  Test double for the `Soundai.TTS` adapter seam (see `Soundai.TTS.adapter/0`).

  Returns a tiny canned WAV so controller tests never touch the real Ortex
  model, which is not committed to the repository.
  """

  alias Soundai.TTS.Wav

  @doc "A tiny valid WAV (one silent sample), generated by the real encoder."
  def wav do
    %{audio: audio} = Wav.encode_to_map([0.0])
    audio
  end

  def synthesize(_text) do
    {:ok, %{audio: wav(), duration_ms: 1, sample_rate: 16_000}}
  end
end
