import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :soundai, SoundaiWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Behind an SSL-terminating proxy in production. SSL/HSTS is handled by the
# upstream terminator, so Phoenix serves plain HTTP and must not redirect.
# Note `:force_ssl` is required to be set at compile-time.
config :soundai, SoundaiWeb.Endpoint, force_ssl: false

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :soundpanel, SoundpanelWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :soundpanel, SoundpanelWeb.Endpoint, force_ssl: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
